### ISSUE TITLE
Shotgun Slugs not working in Weapon Calculator

### ISSUE THREAD

**Issue by RathfulConcepts** [TCF-Wiki/TCF-Apps#8]
**Describe the bug**

Shotgun Slugs Converter in the Attachments section of the Weapon Calculator does not change the effective range of the weapon on expanded stats or Fall off chart

**To Reproduce**
1. Go to Weapon Calculator
2. Click on any shotgun and apply Shotgun Slug Converter
3. Open Expanded Stats and goto Falloff Range
4. View Fall Off Chart at the bottom
5. See error

**Expected behavior**

Fall off would change with use of Shotgun Slug Converter

**Screenshots**
![image_2023-03-10_141959656](https://user-images.githubusercontent.com/92061704/224406770-5d17b274-a915-4890-aed7-b23e12df3a99.png)
![image](https://user-images.githubusercontent.com/92061704/224406992-0363ee12-3f54-49d5-87db-b756dd340b7f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: OperaGX
 - Version: Chromium v.109.0.5414.120

**Additional context**

**Comment by VeryGreatFrog** [comment]
This has been fixed in the most recent update.
